import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/dm-sans/latin-700.css';
import '@fontsource/manrope/latin-600.css';
import '@fontsource/manrope/latin-700.css';
import '@fontsource/manrope/latin-800.css';
import { ArrowUpRight, ArrowRight, Plus, LayoutDashboard, Activity, Users, Target, ShieldCheck, LockKeyhole, Globe, Heart, ChevronRight, X, Check, CheckCircle2, Clock3, CalendarDays, Flame, Leaf, CircleHelp, Settings2, Download, Trash2, Flag, Eye, LogOut, LoaderCircle, Sparkles, Send, Volleyball, Dumbbell, CircleDot, TrendingUp } from 'lucide-react';
import './styles.css';

const iconFor = { Bowling: CircleDot, Batting: Activity, Fielding: Volleyball, Strength: Dumbbell, Recovery: Leaf };
const typeClass = t => t.toLowerCase();
const niceDate = d => new Date(d+'T12:00:00Z').toLocaleDateString('en-IN',{day:'numeric',month:'short'});
const today = () => new Date().toISOString().slice(0,10);
const ErrorContext = React.createContext('');
async function api(path,method='GET',payload) { const response=await fetch('/api'+path,{method,headers:payload?{'Content-Type':'application/json'}:{},body:payload?JSON.stringify(payload):undefined}); const value=await response.json(); if(!response.ok)throw new Error(value.error||'Something went wrong.');return value; }
function Badge({children,tone=''}){return <span className={'badge '+tone}>{children}</span>}
function TypeIcon({type}) {const Icon=iconFor[type]||Activity;return <span className={'type-icon '+typeClass(type)}><Icon size={20}/></span>}
function PitchArt(){return <svg className="pitch-art" viewBox="0 0 430 270" aria-hidden="true"><g fill="none" stroke="currentColor"><ellipse cx="240" cy="138" rx="164" ry="105" strokeWidth="1"/><ellipse cx="240" cy="138" rx="121" ry="78" strokeDasharray="4 6"/><path d="M206 84h67v110h-67z"/><path d="M195 101h90M195 175h90"/><path d="M231 89v11m8-11v11m8-11v11M231 176v12m8-12v12m8-12v12" strokeWidth="3"/><path d="M242 165Q280 91 348 65" strokeWidth="2" strokeDasharray="5 5"/></g><circle cx="349" cy="64" r="10" fill="#d7f17b"/><path d="M344 57q-2 8 10 14" fill="none" stroke="#203d2e" strokeWidth="1.5"/><g transform="translate(94 42) rotate(-28)"><rect width="17" height="63" rx="5" fill="#d7f17b"/><rect x="5" y="-25" width="7" height="28" rx="2" fill="#eeeacb"/><path d="M8 7v40" stroke="#9bb956"/></g><circle cx="317" cy="213" r="4" fill="currentColor"/><circle cx="141" cy="192" r="4" fill="currentColor"/><circle cx="189" cy="55" r="4" fill="currentColor"/></svg>}
function Modal({title,children,onClose,wide=false}){
 const formError=React.useContext(ErrorContext);
 const ref=useRef();useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>{previous?.focus?.();};},[]);
 return <dialog ref={ref} className={'modal '+(wide?'wide':'')} onCancel={onClose} onClick={e=>{if(e.target===ref.current){const r=ref.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}} aria-labelledby="modal-title"><div className="modal-heading"><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={21}/></button></div>{formError&&<p className="form-error" role="alert">{formError}</p>}{children}</dialog>
}
function App(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[page,setPage]=useState('overview'),[modal,setModal]=useState(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[filter,setFilter]=useState('All'),[feedTab,setFeedTab]=useState('All updates');
 const [formError,setFormError]=useState('');
 useEffect(()=>{setFormError('')},[modal?.type]);
 const toastTimer=useRef(); const notify=text=>{setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500);};
 async function load(){setError('');try{setData(await api('/state'));}catch(e){setError(e.message);}}
 useEffect(()=>{load();return()=>clearTimeout(toastTimer.current)},[]);
 async function act(path,method,payload,message,close=false){setBusy(true);setFormError('');try{setData(await api(path,method,payload));if(close)setModal(null);if(message)notify(message);return true;}catch(e){setFormError(e.message);notify(e.message);return false;}finally{setBusy(false);}}
 async function changePerspective(role){const ok=await act('/perspective','POST',{role},'Demo perspective changed');if(ok){setPage(role==='athlete'?'overview':role==='coach'?'journey':'community');setModal(null);}}
 if(!data)return <div className="loading-screen"><div className="brand"><span className="brand-mark">p<span>↗</span></span>pitchup<span className="brand-dot">.</span></div>{error?<><h1>We couldn’t load your clubhouse.</h1><p>{error}</p><p>Start the local server with <code>npm run dev</code>.</p><button className="button primary" onClick={load}>Try again</button></>:<><LoaderCircle className="spin"/><p>Getting your cricket ready…</p></>}</div>;
 const owner=data.perspective==='athlete',coach=data.perspective==='coach',p=data.profile,s=data.summary;
 const nav=[['overview','Overview',LayoutDashboard],['journey','My journey',Activity],['community','Club feed',Users],['challenge','Challenges',Target],['settings','Privacy & profile',ShieldCheck]];
 const openRecord=()=>setModal({type:'record'});
 const openActivity=a=>setModal({type:'detail',id:a.id});
 const detail=modal?.id?data.activities.find(a=>a.id===modal.id):null;
 const filtered=data.activities.filter(a=>filter==='All'||a.type===filter);
 const posts=data.posts.filter(post=>feedTab!=='My milestones'||post.owned);
 const greeting=owner?'Make your next move.':coach?'Support the next step.':'Every journey deserves a cheer.';
 function ActivityRow({a}){return <button className="activity-row" onClick={()=>openActivity(a)}><TypeIcon type={a.type}/><div className="activity-copy"><strong>{a.title}</strong><span>{a.type} <i>·</i> {niceDate(a.date)} <i>·</i> {a.duration} min{a.balls>0?` · ${a.balls} deliveries`:''}</span></div><span className="row-visibility">{a.visibility==='private'?<LockKeyhole size={13}/>:a.visibility==='club'?<Users size={13}/>:<Globe size={13}/>} {a.visibility==='private'?'Private':a.visibility==='club'?'Club':'Public'}</span><ChevronRight size={17}/></button>}
 function FeedPost({post}){return <article className="feed-post"><div className="post-byline"><span className={'avatar '+(post.owned?'':'alternate')}>{post.initials}</span><div><strong>{post.author}</strong><span>{post.role} <i>·</i> Demo player</span></div><span className="post-audience">{post.visibility==='club'?<Users size={13}/>:<Globe size={13}/>} {post.visibility}</span></div><div className="post-body"><span className={'tiny-label '+typeClass(post.type)}>{post.type.toUpperCase()}</span><h3>{post.title}</h3><p>{post.summary}</p><div className="milestone-rule"><span/><span/><span/></div></div><div className="post-footer"><button disabled={!owner||busy} className={'cheer '+(post.cheered?'active':'')} onClick={()=>act('/cheer','POST',{id:post.id},post.cheered?'Cheer removed':'A little encouragement goes a long way')}><Heart size={17} fill={post.cheered?'currentColor':'none'}/>{post.cheered?'You cheered':'Send a cheer'}</button>{owner&&post.owned?<button className="text-button" onClick={()=>setModal({type:'share',id:post.id})}>Manage sharing <ArrowUpRight size={14}/></button>:owner?<button className="icon-button" aria-label={'Report '+post.author+' post'} onClick={()=>setModal({type:'report',post})}><Flag size={15}/></button>:<span className="subtle">Shared milestone</span>}</div></article>}
 function Insight(){const hindi=p.language==='hi';return <article className="insight card"><div className="section-top"><span className="eyebrow"><Sparkles size={15}/> TRAINING NOTES</span><Badge>Rule-based demo</Badge></div><h3>{hindi?'आपका सप्ताह, आपकी प्रगति':s.status}</h3><p>{hindi?`इस सप्ताह आपने ${s.bowling} गेंदें दर्ज की हैं। आपकी दर्ज की गई योजना ${p.plannedBowling} गेंदों की है। यह तुलना है, अतिरिक्त प्रशिक्षण की सलाह नहीं।`:s.explanation}</p><div className="insight-foot"><ShieldCheck size={16}/><span>Based only on logged activity. No health or readiness prediction.</span></div><button className="text-button" onClick={()=>setModal({type:'insight'})}>See how this works <ArrowRight size={15}/></button></article>}
 return <ErrorContext.Provider value={formError}><div className="app-shell">
  <aside className="sidebar"><a href="#" className="brand" onClick={e=>{e.preventDefault();setPage(owner?'overview':'community')}} aria-label="PitchUp home"><span className="brand-mark">p<span>↗</span></span>pitchup<span className="brand-dot">.</span></a><div className="sidebar-kicker">YOUR GAME. YOUR GROWTH.</div><nav aria-label="Main navigation">{nav.map(([id,label,Icon])=><button key={id} className={'nav-item '+(page===id?'selected':'')} aria-current={page===id?'page':undefined} onClick={()=>setPage(id)}><Icon size={20}/><span>{label}</span>{page===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-club"><span className="eyebrow">YOUR CLUBHOUSE</span><button onClick={()=>setPage('community')} className="club-link"><span className="club-monogram">BC</span><span>Boundary Collective<small>Women’s cricket · Demo club</small></span></button></div><div className="sidebar-bottom"><div className="purpose"><span className="purpose-ball">✳</span><p>More than a match.<br/><strong>A journey of your own.</strong></p></div><button className="sidebar-profile" onClick={()=>setPage('settings')}><span className="avatar">{p.initials}</span><span>{p.name}<small>{owner?'Your demo profile':coach?'Demo coach view':'Public viewer'}</small></span><Settings2 size={17}/></button></div></aside>
  <main className="main"><header className="topbar"><span className="breadcrumb">YOUR CLUBHOUSE <span>/</span> {nav.find(n=>n[0]===page)?.[1]}</span><div className="topbar-controls"><Badge tone="demo"><span className="status-dot"/>Fictional demo</Badge><label className="perspective-label"><Eye size={15}/><select aria-label="Demo perspective" value={data.perspective} disabled={busy} onChange={e=>changePerspective(e.target.value)}><option value="athlete">Athlete view</option><option value="coach">Demo coach</option><option value="visitor">Public viewer</option></select></label></div></header>
  <div className="content"><div className="page-heading"><div><p className="eyebrow">{owner?`WELCOME BACK, ${p.name.split(' ')[0].toUpperCase()}`:coach?'FICTIONAL COACH WORKSPACE':'THE PUBLIC VIEW'}</p><h1>{greeting}</h1><p className="lead">{owner?'Your cricket, your progress, your people.':coach?'Review only the sessions a player has chosen to share.':'Celebrate selected milestones. Private training stays private.'}</p></div>{owner&&<button className="button primary record-main" onClick={openRecord}><Plus size={19}/>Record activity</button>}</div>
  {!owner&&<div className="perspective-banner"><ShieldCheck size={19}/><p><strong>{coach?'Demo coach perspective':'Public viewer perspective'}</strong> {coach?'Private reflections are excluded from these records. Reviews here are simulations.':'Only public milestone posts are available. Session details and private notes are not returned.'} This switch demonstrates permissions; it is not production authentication.</p><button className="text-button" disabled={busy} onClick={()=>changePerspective('athlete')}>Back to athlete <ArrowRight size={16}/></button></div>}
  {page==='overview'&&owner&&<>
   <section className="hero"><div className="hero-copy"><span className="hero-tag">BUILT AROUND WOMEN IN CRICKET</span><h2>Your next chapter<br/>starts in the nets.</h2><p>Every session is part of your story.<br/>Make space for practice, recovery, and progress.</p><button className="button lime" onClick={openRecord}>Let’s get a session in <ArrowUpRight size={18}/></button></div><PitchArt/><div className="hero-caption"><span/> KEEP SHOWING UP, ON YOUR TERMS.</div></section>
   <div className="dashboard-grid"><div className="main-column"><section className="week-section"><div className="section-heading"><h2>Your week at a glance</h2><span><CalendarDays size={14}/> This week</span></div><div className="stats"><div><span>Sessions recorded</span><strong>{s.sessions}<small> / {p.weeklySessions} planned</small></strong><p>Recovery sessions count, too</p></div><div><span>Time for your game</span><strong>{s.minutes}<small> min</small></strong><p>Across your logged activities</p></div><div><span>Bowling deliveries</span><strong>{s.bowling}<small> / {p.plannedBowling||'—'} planned</small></strong><p>A record, not a target to chase</p></div></div><div className="week-chart" role="img" aria-label={'Daily recorded minutes: '+s.days.map(d=>`${niceDate(d.date)} ${d.minutes} minutes`).join(', ')}>{s.days.map((d,i)=><div key={d.date} className={d.date===today()?'today':''}><div className="bar-track"><div style={{height:d.minutes?`${Math.max(8,d.minutes/Math.max(...s.days.map(x=>x.minutes),1)*100)}%`:'4px'}}/><span>{d.minutes?`${d.minutes}m`:''}</span></div><span>{['M','T','W','T','F','S','S'][i]}</span></div>)}</div></section>
   <section className="card activities-card"><div className="section-heading"><h2>Your recent sessions</h2><button className="text-button" onClick={()=>setPage('journey')}>View all <ArrowUpRight size={15}/></button></div>{data.activities.slice(0,3).map(a=><ActivityRow key={a.id} a={a}/>)}{!data.activities.length&&<Empty title="Your journey starts with one session." text="Log a little of what you did. Your record is private until you choose to share." action={openRecord}/>}</section>
   <section><div className="section-heading"><h2>Around the clubhouse</h2><button className="text-button" onClick={()=>setPage('community')}>Open feed <ArrowUpRight size={15}/></button></div>{data.posts.slice(0,1).map(post=><FeedPost key={post.id} post={post}/>)}</section></div>
   <aside className="right-column"><Insight/><article className="goal-card card"><div className="section-top"><span className="eyebrow"><Target size={15}/> YOUR NORTH STAR</span><button className="icon-button" aria-label="Edit goal" onClick={()=>setModal({type:'profile'})}><Settings2 size={16}/></button></div><h3>{p.goal}</h3><div className="progress-label"><span>This week’s sessions</span><strong>{s.sessions}/{p.weeklySessions}</strong></div><div className="progress-track"><span style={{width:Math.min(s.sessions/p.weeklySessions*100,100)+'%'}}/></div><p>Your plan can include rest. There’s no leaderboard here.</p></article><article className="club-promo"><div className="club-graphic"><span>BC</span><i/><i/></div><span className="eyebrow">BOUNDARY COLLECTIVE</span><h3>Find your people.<br/>Grow your game.</h3><p>A fictional women’s cricket club built for this demo.</p><button className="text-button" onClick={()=>setPage('community')}>Step into the clubhouse <ArrowUpRight size={16}/></button></article></aside></div>
  </>}
  {page==='journey'&&(owner||coach)&&<section className="journey-page"><div className="section-heading"><div><h2>{coach?'Shared for coach review':'A record of showing up'}</h2><p className="subtle">{coach?'Only explicitly shared sessions appear here.':'Self-reported sessions. Progress is personal, and every record belongs to you.'}</p></div><Badge>{data.activities.length} sessions</Badge></div><div className="filter-tabs" aria-label="Filter activities">{['All','Bowling','Batting','Fielding','Strength','Recovery'].map(t=><button aria-pressed={filter===t} className={filter===t?'active':''} onClick={()=>setFilter(t)} key={t}>{t}</button>)}</div><div className="card">{filtered.map(a=><ActivityRow key={a.id} a={a}/>)}{!filtered.length&&<Empty title={coach?'No shared sessions here.':'No sessions in this view yet.'} text={coach?'A player must explicitly enable coach access.':'Try another filter or record your next session.'} action={owner?openRecord:null}/>}</div>{owner&&<div className="note-box"><LockKeyhole size={19}/><p>Your session notes always stay private. Coach access and milestone sharing are separate choices.</p></div>}</section>}
  {page==='community'&&<div className="community-grid"><section><div className="club-header"><span className="club-monogram large">BC</span><div><span className="eyebrow">WOMEN’S CRICKET · FICTIONAL DEMO CLUB</span><h2>Boundary Collective</h2><p>A space to practice, connect, and back each other.</p></div></div><div className="filter-tabs"><button className={feedTab==='All updates'?'active':''} onClick={()=>setFeedTab('All updates')}>All updates</button>{owner&&<button className={feedTab==='My milestones'?'active':''} onClick={()=>setFeedTab('My milestones')}>My milestones</button>}</div>{posts.map(post=><FeedPost key={post.id} post={post}/>)}{!posts.length&&<Empty title="No shared milestones yet." text="Private sessions never appear automatically. Open a session to choose what you share."/>}</section><aside><article className="card community-guidelines"><span className="eyebrow"><ShieldCheck size={15}/> THE CLUBHOUSE CODE</span><h3>Encouragement over comparison.</h3><p>Celebrate the effort. Respect the boundaries. Let every player own her story.</p><ul><li>Ask before sharing someone’s story.</li><li>Keep locations and health details private.</li><li>Rest is part of training.</li><li>Report unwanted or inappropriate content.</li></ul><Badge>Demo community · No real members</Badge></article>{owner&&<article className="card share-cta"><Send size={23}/><h3>Something worth celebrating?</h3><p>Choose a session from your journey and share a milestone, on your terms.</p><button className="button secondary" onClick={()=>setPage('journey')}>Choose a session <ArrowRight size={16}/></button></article>}</aside></div>}
  {page==='challenge'&&owner&&<div className="challenge-layout"><article className="challenge-feature"><span className="eyebrow">THE BOUNDARY COLLECTIVE · DEMO CHALLENGE</span><div className="challenge-emblem"><Target size={58}/></div><h2>Your plan.<br/>Your pace.</h2><p>Make a little room for your cricket this week. Follow your own entered plan, record your sessions, and include recovery without breaking a streak.</p><div className="challenge-progress"><strong>{s.sessions} <span>/ {p.weeklySessions} planned sessions logged</span></strong><div className="progress-track"><span style={{width:Math.min(s.sessions/p.weeklySessions*100,100)+'%'}}/></div></div><button disabled={busy} className={'button '+(data.challengeJoined?'secondary':'primary')} onClick={()=>act('/challenge','POST',{},data.challengeJoined?'You left the demo challenge':'You joined Your plan. Your pace.')}><CheckCircle2 size={18}/>{data.challengeJoined?'Joined · Leave challenge':'Join this week’s challenge'}</button><small>Joining records participation locally. No prizes or real club participation.</small></article><article className="card"><h3>Consistency without the pressure.</h3><div className="principle"><Leaf/><div><strong>Recovery belongs here</strong><p>Recovery sessions count in your record. More training is not automatically better.</p></div></div><div className="principle"><Target/><div><strong>Follow your own plan</strong><p>Goals are entered by you, ideally with your coach. We don’t prescribe workload.</p></div></div><div className="principle"><Heart/><div><strong>No volume leaderboard</strong><p>There’s no reward for logging more balls than someone else.</p></div></div><button className="text-button" onClick={()=>setModal({type:'profile'})}>Adjust my plan <ArrowUpRight size={15}/></button></article></div>}
  {page==='settings'&&owner&&<div className="settings-grid"><article className="card profile-card"><span className="avatar extra-large">{p.initials}</span><h2>{p.name}</h2><p>{p.role} · Demo player</p><Badge tone="green">Women-first cricket development</Badge><div className="profile-goal"><span className="eyebrow">YOUR GOAL</span><p>{p.goal}</p></div><button className="button secondary" onClick={()=>setModal({type:'profile'})}><Settings2 size={17}/>Edit profile & plan</button></article><section><article className="card"><div className="section-heading"><h2>Your story. Your boundaries.</h2><ShieldCheck size={23}/></div><div className="setting-row"><div><strong>New activities are private</strong><p>Sharing is always an explicit choice after recording.</p></div><Badge tone="green"><LockKeyhole size={12}/>Always on</Badge></div><div className="setting-row"><div><strong>Private reflections</strong><p>Never included in coach or public responses.</p></div><ShieldCheck size={20}/></div><div className="setting-row"><div><strong>Location tracking</strong><p>This prototype does not collect precise location.</p></div><Badge>Off</Badge></div><div className="setting-row"><div><strong>Export your record</strong><p>Download your profile and sessions as JSON.</p></div><button className="button secondary small" onClick={async()=>{try{const v=await api('/export');const url=URL.createObjectURL(new Blob([JSON.stringify(v,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='pitchup-my-record.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Your record has been downloaded');}catch(e){notify(e.message)}}}><Download size={16}/>Export</button></div></article><div className="note-box"><CircleHelp size={20}/><p><strong>Local prototype.</strong> All sample people and club content are fictional. Data is stored on this computer. Perspective switching is for demonstration, not identity verification. Don’t enter sensitive real-world information.</p></div></section></div>}
  {(!owner&&['overview','challenge','settings'].includes(page)||(!owner&&!coach&&page==='journey'))&&<Empty title="This belongs to the athlete." text="Personal goals, activity history, and settings aren’t available in this perspective."/>}
  <footer className="page-footer"><span>pitchup. <i>Made for the journey.</i></span><span>Local prototype · Fictional players & club · No ICC affiliation claimed</span></footer>
  </div></main>
  {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={16}/></button></div>}
  {modal?.type==='record'&&<Modal title="Make this session part of your story." onClose={()=>setModal(null)} wide><p className="modal-intro">A quick record of what you did. It starts private.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await act('/activities','POST',{...Object.fromEntries(f),shareWithCoach:f.get('shareWithCoach')==='on'},'Session saved privately. Your journey is updated.',true);}}><RecordFields/><div className="modal-actions"><span><LockKeyhole size={14}/>Only you, unless you choose otherwise</span><button disabled={busy} className="button primary" type="submit">{busy?<LoaderCircle className="spin" size={17}/>:<Plus size={17}/>}Save session</button></div></form></Modal>}
  {modal?.type==='detail'&&detail&&<Modal title={detail.title} onClose={()=>setModal(null)}><div className="detail-type"><TypeIcon type={detail.type}/><div><strong>{detail.type}</strong><p>{niceDate(detail.date)} · Self-reported demo activity</p></div></div><div className="detail-metrics"><div><span>Duration</span><strong>{detail.duration}<small> min</small></strong></div>{detail.balls>0&&<div><span>Deliveries</span><strong>{detail.balls}</strong></div>}<div><span>Reported effort</span><strong>{detail.effort}<small> / 10</small></strong></div></div>{owner&&<div className="private-reflection"><span className="eyebrow"><LockKeyhole size={14}/> PRIVATE REFLECTION</span><p>{detail.notes||'No private reflection added.'}</p></div>}<div className="setting-row"><div><strong>{detail.review?'Demo review completed':'Not reviewed'}</strong><p>{detail.review?'This is a simulated review, not professional advice.':'No coaching or clinical conclusion has been made.'}</p></div>{detail.review&&<CheckCircle2 size={20}/>}</div>{owner?<><label className="checkbox-row"><input type="checkbox" checked={detail.shareWithCoach} disabled={busy} onChange={e=>act('/activities/'+detail.id,'PATCH',{shareWithCoach:e.target.checked},'Coach access updated')}/><span>Share session measurements with the demo coach<small>Your private reflection is never shared.</small></span></label><div className="modal-actions"><button className="text-button danger" onClick={()=>setModal({type:'delete',id:detail.id})}><Trash2 size={15}/>Delete</button><button className="button primary" onClick={()=>setModal({type:'share',id:detail.id})}>Choose milestone audience <ArrowUpRight size={16}/></button></div></>:<div className="modal-actions"><button disabled={busy||!!detail.review} className="button primary" onClick={()=>act('/activities/'+detail.id+'/review','POST',{},'Demo review recorded',true)}><Check size={16}/>{detail.review?'Already reviewed':'Mark reviewed in demo'}</button></div>}</Modal>}
  {modal?.type==='share'&&detail&&<Modal title="Share the milestone. Keep the details." onClose={()=>setModal(null)}><p className="modal-intro">Your post includes your name, role, activity title, type, date, and the summary below. Check the title for anything personal before publishing.</p><div className="share-preview"><span className="eyebrow">MILESTONE PREVIEW</span><h3>{detail.title}</h3><p>Completed a {detail.type.toLowerCase()} session as part of a personal cricket journey.</p><small>{p.name} · {p.role} · {niceDate(detail.date)}</small></div><div className="note-box"><ShieldCheck size={18}/><p>Private notes, effort, duration, delivery counts, and coach feedback stay out of this post.</p></div><form onSubmit={e=>{e.preventDefault();act('/activities/'+detail.id,'PATCH',{visibility:new FormData(e.currentTarget).get('visibility')},'Milestone audience updated',true)}}><fieldset className="audience-options"><legend>Who can see this milestone?</legend>{[['private',LockKeyhole,'Only me','Keep the session off the feed.'],['club',Users,'My club','Visible in the demo club, not the public view.'],['public',Globe,'Public','Visible in the public viewer perspective.']].map(([value,Icon,label,help])=><label key={value}><input type="radio" name="visibility" value={value} defaultChecked={detail.visibility===value}/><Icon size={20}/><span><strong>{label}</strong><small>{help}</small></span></label>)}</fieldset><div className="modal-actions"><button className="button primary" disabled={busy} type="submit">Save audience <Check size={17}/></button></div></form></Modal>}
  {modal?.type==='delete'&&<Modal title="Delete this session?" onClose={()=>setModal(null)}><p className="modal-intro">Its measurements, private reflection, and hosted milestone will be removed. This cannot remove copies already exported or saved elsewhere.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Keep session</button><button className="button destructive" disabled={busy} onClick={()=>act('/activities/'+modal.id,'DELETE',undefined,'Session deleted',true)}>Delete session</button></div></Modal>}
  {modal?.type==='profile'&&<Modal title="A plan that belongs to you." onClose={()=>setModal(null)}><p className="modal-intro">These are your entered goals, not prescribed training. Set them with a qualified coach where possible.</p><form onSubmit={e=>{e.preventDefault();act('/profile','PATCH',Object.fromEntries(new FormData(e.currentTarget)),'Profile and plan saved',true)}}><label className="field">Display name<input name="name" defaultValue={p.name} maxLength={60} required/></label><label className="field">Cricket role<select name="role" defaultValue={p.role}>{['Pace bowler','Spin bowler','Batter','All-rounder','Wicketkeeper'].map(r=><option key={r}>{r}</option>)}</select></label><label className="field">My goal<input name="goal" defaultValue={p.goal} required maxLength={160}/></label><div className="form-grid"><label className="field">Planned sessions / week<input name="weeklySessions" type="number" min="1" max="14" defaultValue={p.weeklySessions} required/></label><label className="field">Planned bowling deliveries<input name="plannedBowling" type="number" min="0" max="1000" defaultValue={p.plannedBowling} required/><small>Use 0 when no bowling plan applies.</small></label></div><label className="field">Training note language<select name="language" defaultValue={p.language}><option value="en">English</option><option value="hi">हिन्दी · Hindi summary</option></select><small>Only the short training summary is translated in this prototype.</small></label><div className="modal-actions"><button className="button primary" disabled={busy} type="submit">Save my plan <Check size={17}/></button></div></form></Modal>}
  {modal?.type==='insight'&&<Modal title="Clarity, without the guesswork." onClose={()=>setModal(null)}><Badge>Rule-based · Not generative AI</Badge><p className="modal-intro">PitchUp totals your logged sessions for the current Monday–Sunday week and compares bowling deliveries with the weekly plan you entered.</p><div className="explain-list"><div><strong>What it knows</strong><p>Session type, recorded date, duration, deliveries, and your entered plan.</p></div><div><strong>What it doesn’t know</strong><p>Unlogged training, medical history, actual physical capacity, or whether your plan is appropriate.</p></div><div><strong>What happens above the plan</strong><p>It asks for a review. It does not diagnose overload or prescribe a new workload.</p></div><div><strong>Future AI integration</strong><p>A constrained language layer could explain verified facts. This build does not call an AI model or send your records to an external service.</p></div></div></Modal>}
  {modal?.type==='report'&&<Modal title="Report and hide this demo post" onClose={()=>setModal(null)}><p className="modal-intro">The post will be hidden locally and your report saved on this computer. No real moderation team is connected.</p><form onSubmit={e=>{e.preventDefault();act('/report','POST',{id:modal.post.id,reason:new FormData(e.currentTarget).get('reason')},'Demo report saved. Post hidden locally.',true)}}><label className="field">Reason<select required name="reason"><option>Unwanted contact</option><option>Inappropriate content</option><option>Other concern</option></select></label><div className="modal-actions"><button className="button primary" disabled={busy}>Save report & hide</button></div></form></Modal>}
 </div></ErrorContext.Provider>
}
function RecordFields(){const [type,setType]=useState('Bowling'),[effort,setEffort]=useState(5);return <><div className="form-grid"><label className="field">Activity type<select name="type" value={type} onChange={e=>setType(e.target.value)}>{Object.keys(iconFor).map(t=><option key={t}>{t}</option>)}</select></label><label className="field">Session date<input name="date" type="date" min="2020-01-01" max={today()} defaultValue={today()} required/></label></div><label className="field">Session title<input name="title" placeholder="e.g. Finding my rhythm in the nets" maxLength={90} required autoFocus/></label><div className="form-grid"><label className="field">Duration (minutes)<input name="duration" type="number" placeholder="45" min="1" max="480" required/></label>{['Bowling','Batting'].includes(type)&&<label className="field">{type==='Bowling'?'Deliveries bowled':'Balls faced'}<input name="balls" type="number" placeholder="36" min="1" max="600" required/></label>}</div><label className="field effort-label">How did the effort feel? <strong>{effort}/10</strong><input name="effort" type="range" min="1" max="10" value={effort} onChange={e=>setEffort(e.target.value)}/><span className="range-labels"><span>Very light</span><span>Very hard</span></span></label><label className="field">Private reflection <span className="optional">Optional · only you</span><textarea name="notes" rows="3" maxLength={1500} placeholder="What did you work on? What would you like to remember?"/></label><label className="checkbox-row"><input name="shareWithCoach" type="checkbox"/><span>Let the demo coach see session measurements<small>Private reflections are excluded. This does not publish a post.</small></span></label></>}
function Empty({title,text,action}){return <div className="empty"><Activity size={30}/><h3>{title}</h3><p>{text}</p>{action&&<button className="button primary" onClick={action}><Plus size={17}/>Record activity</button>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
